#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Rodrigo França Scoropad

# Short bio or description (displayed in the header)
description: Estagiário de desenvolvimento de aplicativos mobile no LACTEC

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://lh3.googleusercontent.com/5co9RWGPLEBF8etTpp_hHzLJMA7cTAh7eN7R5XO42a0WvPznb409c91SIr3EB-HreCK7i0p8RVk6IPKvXx0VAVnEsBvVzCM8UjnSyZUzYcPjjLThQP5Oa9E8U1FDjTQ-lPauJFj2QI78r_WP_c6SGpfGyrgDa3yBbhZJcuo_3vYUvZ4XnfZfKYxj_61xNeOhjg5yaugFkEI6pxrs_0x4CeDG2-_OP2fXsjy1UZgRO51YuTerPLEoD-7z0FDgfsTL68ZJzk9TjHXckjSGXbbKPiqExIhsLGp09_seRlq5TCHN-6rzbs3OK1Q_31xoJy-m9rR7-S1SFTySyLaGSJF3midOv51t48masRTZ6BDpPeaFneIyqmBLHb_ahlNpDs-z50TloRJyNQz8E6jyfUTsfBihYA2YqF2ui9sE2Fbb0NFH50M9rb6iAbNClYvEvLZK5-S6sbV_X-PhOWIOczBJ1WhcwMX64vf7xwZWYMvj_ghNVsRDOhuPxuPacYOV6Gwn7dJ7JBVNQGFt7P0-gyMif6sB0oe1_JJ1JCp6-IruIzxjkdhNTAEDUSDqYgzt63WH6OHnc9-EsAUz3tttP079mHVFClf8tDUzy5TkHO2_2HYHScPcjSvOMdEk7nihugfkT9R-kTYkZSXff0AvGL2j9x4f57MqRFcDsRH1_LSmHa-Y17Jzp-o3L8GXLsf8vztZuuRu8n2Xlf6af1dS_w=s140-no

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: rodrigo-fs
  instagram:
  linkedin: rodrigo-fran%C3%A7a-4372a6153
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: rodrigo-fs.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
